services:
  backend-database:
    image: mysql
    container_name: mysql_todo_db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'todo',
          '-ppassword',
        ]
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 10s

  backend-express:
    container_name: backend-express
    restart: on-failure
    build:
      context: .
      dockerfile: apps/backend-express/backend.Dockerfile
    environment:
      DB_HOST: backend-database
      DB_USER: todo
      DB_PASSWORD: password
      DB_NAME: todo_db
    ports:
      - '3333:3333'
    depends_on:
      backend-database:
        condition: service_healthy

  frontend-react:
    container_name: frontend-react
    restart: on-failure
    build:
      context: .
      dockerfile: apps/frontend/frontend.Dockerfile
    environment:
      VITE_BASE_URL: backend-express
    ports:
      - '3000:80'
    depends_on:
      - backend-express

volumes:
  db_data:
